### ISSUE TITLE
BUUCTF 2018 Online Tool - scr1pt_k1ddi3' blog

### ISSUE THREAD

**Issue by scr1pt-k1ddi3** [scr1pt-k1ddi3/scr1pt-k1ddi3.github.io#5]
https://scr1pt-k1ddi3.github.io/2022/04/17/Tool/ 

 <?php  if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) &#123;     $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR']; &#125;  if(!isset($_GET['host'])) &#123;

**Comment by scr1pt-k1ddi3** [comment]
zzc

**Comment by 1amfree** [comment]
tql
